//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Magazine.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurrentViolation
    {
        public int CurrentViolationID { get; set; }
        public Nullable<int> ViolationID { get; set; }
        public string Responsible { get; set; }
        public string UsingSanctions { get; set; }
        public string DisposalCheck { get; set; }
        public string PayCheck { get; set; }
        public string DispTime { get; set; }
        public Nullable<int> RevisionID { get; set; }
    
        public virtual Revision Revision { get; set; }
        public virtual Violation Violation { get; set; }
    }
}
