//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Magazine.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Revision
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Revision()
        {
            this.CurrentViolations = new HashSet<CurrentViolation>();
        }
    
        public int RevisionID { get; set; }
        public Nullable<int> EnterpriseID { get; set; }
        public Nullable<int> InspectorID { get; set; }
        public string RevisionDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CurrentViolation> CurrentViolations { get; set; }
        public virtual Enterprise Enterprise { get; set; }
        public virtual Inspector Inspector { get; set; }
    }
}
